// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PlacaSegura.Infrastructure.Persistence;

#nullable disable

namespace PlacaSegura.Infrastructure.Migrations
{
    [DbContext(typeof(PlacaSeguraDbContext))]
    partial class PlacaSeguraDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PlacaSegura.Domain.Entities.Claim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptsCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FoundReportId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LostReportId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("FoundReportId");

                    b.HasIndex("LostReportId");

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("PlacaSegura.Domain.Entities.LostSecret", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uuid");

                    b.Property<string>("SecretHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecretSalt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ReportId")
                        .IsUnique();

                    b.ToTable("LostSecrets");
                });

            modelBuilder.Entity("PlacaSegura.Domain.Entities.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FoundReportId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LostReportId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SafeLocationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FoundReportId");

                    b.HasIndex("SafeLocationId");

                    b.HasIndex("LostReportId", "FoundReportId")
                        .IsUnique();

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("PlacaSegura.Domain.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SenderUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SenderUserId");

                    b.HasIndex("MatchId", "CreatedAt");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("PlacaSegura.Domain.Entities.OtpRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("OtpRequests");
                });

            modelBuilder.Entity("PlacaSegura.Domain.Entities.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("EventAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Neighborhood")
                        .HasColumnType("text");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<string>("PlateMasked")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlateNormalizedHash")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("EventAt");

                    b.HasIndex("City", "PlateMasked", "Status");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("PlacaSegura.Domain.Entities.ReportFlag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ReportId");

                    b.ToTable("ReportFlags");
                });

            modelBuilder.Entity("PlacaSegura.Domain.Entities.SafeLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Neighborhood")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SafeLocations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Address = "Rua Principal, 100",
                            City = "São Paulo",
                            IsActive = true,
                            Name = "Delegacia Central",
                            Neighborhood = "Centro"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Address = "Av. Norte, 500",
                            City = "São Paulo",
                            IsActive = true,
                            Name = "Posto Policial Norte",
                            Neighborhood = "Santana"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Address = "Av. Sul, 200",
                            City = "São Paulo",
                            IsActive = true,
                            Name = "Base Comunitária Sul",
                            Neighborhood = "Santo Amaro"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Address = "Rua do Shopping, 1",
                            City = "São Paulo",
                            IsActive = true,
                            Name = "Shopping Center Plaza",
                            Neighborhood = "Jardins"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Address = "Rua Segura, 99",
                            City = "Rio de Janeiro",
                            IsActive = true,
                            Name = "Estacionamento 24h Seguro",
                            Neighborhood = "Centro"
                        });
                });

            modelBuilder.Entity("PlacaSegura.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PlacaSegura.Domain.Entities.Claim", b =>
                {
                    b.HasOne("PlacaSegura.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlacaSegura.Domain.Entities.Report", "FoundReport")
                        .WithMany()
                        .HasForeignKey("FoundReportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlacaSegura.Domain.Entities.Report", "LostReport")
                        .WithMany()
                        .HasForeignKey("LostReportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("FoundReport");

                    b.Navigation("LostReport");
                });

            modelBuilder.Entity("PlacaSegura.Domain.Entities.LostSecret", b =>
                {
                    b.HasOne("PlacaSegura.Domain.Entities.Report", "Report")
                        .WithOne()
                        .HasForeignKey("PlacaSegura.Domain.Entities.LostSecret", "ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("PlacaSegura.Domain.Entities.Match", b =>
                {
                    b.HasOne("PlacaSegura.Domain.Entities.Report", "FoundReport")
                        .WithMany()
                        .HasForeignKey("FoundReportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlacaSegura.Domain.Entities.Report", "LostReport")
                        .WithMany()
                        .HasForeignKey("LostReportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlacaSegura.Domain.Entities.SafeLocation", "SafeLocation")
                        .WithMany()
                        .HasForeignKey("SafeLocationId");

                    b.Navigation("FoundReport");

                    b.Navigation("LostReport");

                    b.Navigation("SafeLocation");
                });

            modelBuilder.Entity("PlacaSegura.Domain.Entities.Message", b =>
                {
                    b.HasOne("PlacaSegura.Domain.Entities.Match", "Match")
                        .WithMany("Messages")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlacaSegura.Domain.Entities.User", "SenderUser")
                        .WithMany()
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("SenderUser");
                });

            modelBuilder.Entity("PlacaSegura.Domain.Entities.Report", b =>
                {
                    b.HasOne("PlacaSegura.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("PlacaSegura.Domain.Entities.ReportFlag", b =>
                {
                    b.HasOne("PlacaSegura.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlacaSegura.Domain.Entities.Report", "Report")
                        .WithMany()
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("PlacaSegura.Domain.Entities.Match", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
